### ISSUE TITLE
DST / EST change resulted in unexpected "submission per day" reset

### ISSUE THREAD

**Issue by bkayes** [eecs-autograder/autograder.io#34]
[This student](https://autograder.io/web/project/1440?current_tab=student_lookup&current_student_lookup=309413) in EECS 280 reported that submissions made between 11PM and Midnight last night (March 12th) were counted as submissions made on March 13th such that they were unable to make any submissions on March 13th because their 3 per day was used up. (There were 4 or 5 other students also reporting this same issue) We have granted a fix by simply granting some bonus submits to all students to alleviate the issue, and the student AG linked above shows that their submits made today are indeed using the bonus submits, and thus it's not just a UI bug like we've seen in the past.

**Comment by james-perretta** [comment]
And here I was thinking I was done dealing with timezone shenanigans... I know we used to see this happen regularly, but then I fixed it, so I'll have to look into it and see what the deal is.

**Comment by james-perretta** [comment]
It looks like the fix for this will be to either use pytz's `.localize` method or to use `ZoneInfo` for timezone's when we upgrade to python 3.9

**Comment by jamesjuett** [comment]
Thanks, James! We're planning for the rest of our projects this term and whether we might need to implement some kind of workaround. What's the timeline for the python 3.9 upgrade (if the fix is dependent on that)?

**Comment by james-perretta** [comment]
@jamesjuett To clarify, this is a different DST issue than the one we had years back and only happens on the day of DST starting (so it won't be a problem until next year). This issue is that the datetime arithmetic across the DST boundary (March 13 before and after 3am or whatever it is) doesn't "just work" the way that it does with newer datetime libraries. March 13 at 12am and 6am, for example, both get translated as UTC -4:00 with the current library even though March 13 at 12am should be UTC -5:00 and March 13 at 6am shoud be UTC -4:00.

**Comment by jamesjuett** [comment]
Got it, thanks for the clarification!

**Comment by james-perretta** [comment]
My apologies, I've made some progress on the fix but haven't been able to deploy it yet.

**Comment by bkayes** [comment]
🎉
