### ISSUE TITLE
Rejected submissions use late day tokens

### ISSUE THREAD

**Issue by thisisbenmanley** [eecs-autograder/autograder.io#35]
A student made multiple invalid submissions the day after the due date for a project. Each of the submissions looks like the screenshot below. There were no valid submissions made by this student that day. And, just in case it's important, this student actually never made a valid submission (the only submissions made by the student to this project were these invalid submissions, the day after the due date).

![image](https://user-images.githubusercontent.com/13109956/160056422-e8ee4208-c4a7-4063-bd22-d9a249e36228.png)

This set of invalid submissions used up one of their late days in the course. I would imagine this is either a bug / unintentional outcome, or this is a feature that should be changed. Late days should only be used by *valid* submissions

**Comment by james-perretta** [comment]
Sure, I'm not opposed to changing this. I'd be curious to hear from a few others if they have a preference (i.e., should late days be refunded on a rejected submission/is submitting "declaring the use of a late day"/how often do you see this happen?). @jamesjuett @amirkamil @awdeorio

If I remember correctly, this was just a design decision based on the tradeoff of the added complexity to implement it (the bookkeeping for late days is more complicated than for bonus submissions) vs. how common it is for a student to start submitting on a late day and not try to get a valid submission in, together with it being relatively easy to manually refund a late day to a student.

**Comment by awdeorio** [comment]
I would never use this feature either way because I don't offer late days.  I can see both sides of this.

It's reasonable for an invalid submission to consume a late day.  You submitted to the autograder after the deadline, sorry, that's the definition of a late day.

It's also reasonable for an invalid submission to *not* consume a late day.  For similar reasons, an invalid submission doesn't count toward the daily submission limit (I think I remember that policy correctly).

In any case, if a student can't get *anything* working even *after* the deadline, then I'm not sure autograder policy is the real solution to the underlying problem.  If it was up to me, I'd go with whatever was easier to implement here.  AKA do nothing.

**Comment by thisisbenmanley** [comment]
It definitely isn't a big problem, it was only applicable for one student (and I haven't personally seen this in previous semesters). I mostly wanted to report the behavior here in case it was unintentional and would be an easy fix. Definitely agree that it's not worth any heavy implementation

**Comment by amirkamil** [comment]
+1 to @awdeorio's comments.
