### ISSUE TITLE
Clock skew for makefiles

### ISSUE THREAD

**Issue by nelsontm** [eecs-autograder/autograder.io#42]
Getting this a lot on EECS 370 P4 F22:
<img width="606" alt="Screenshot 2022-12-01 at 18 05 03" src="https://user-images.githubusercontent.com/55003080/205177769-96b088c8-1ff0-478f-b522-9c9b7cbf4d7c.png">
cache.c is the student submitted file, so it seems like the submission time is recorded as being in the future to the setup environment's clock.
(Not sure if this is the right place to post this - please advise!)

**Comment by james-perretta** [comment]
Hmm interesting, I'll have to take a look at the servers and see if there's anything I can do about this? Does make still run the build even with this warning? I would imagine that you're building from scratch, and so the modification checks might not matter.

(For things that are likely infrastructure-related, you can email help@autograder.io so that we can keep the issue tracker for feature requests/bug reports and the like :) ).

**Comment by nelsontm** [comment]
Hmm, the help@autograder.io email address bounced. For now I'll continue here:
Everything is still making since we are making from scratch, but our main issue is that it's exiting make with error code 1 which is confusing students. Do you know if there's a way to ignore clock skew for make? That would solve our issue.

**Comment by james-perretta** [comment]
@nelsontm Thanks for the heads up--I contacted DCO and apparently the server handling those emails is kaput. They're working on getting it up and running again.

To make Make go with it, you could maybe try the `--always-make`/`-B` option? That tells make to always rebuild targets, so it might not check timestamps. Let me know if that works.

**Comment by james-perretta** [comment]
I'm going to go ahead and close this. The help@autograder.io email address is working again (the machine handling it needed to be replaced), so please reach out to me there if -B doesn't solve the issue :)
