### ISSUE TITLE
Autograder can't be reached (connection refused).

### ISSUE THREAD

**Issue by jbaileyhandle** [eecs-autograder/autograder.io#44]
![image](https://user-images.githubusercontent.com/65255558/206859129-04cded17-6b11-40fe-b5e2-2da13b83791a.png)

**Comment by lslavice** [comment]
same for me :( and two other ENGR 101 people

**Comment by james-perretta** [comment]
Hi all, A few of the machines didn't come back up properly after the electrical work today. I rebooted those machines and it appears to be up and running again.

For future things like this (things that aren't feature requests or software bug reports), please email me at help@autograder.io so that we can keep the issue tracker clean. :)
