### ISSUE TITLE
Extremely slow (or hanging) reruns

### ISSUE THREAD

**Issue by jbaileyhandle** [eecs-autograder/autograder.io#45]
When rerunning submissions, status either stays at 0% forever or progresses incredibly slowly ( < 1% per minute). This was observed when trying to rerun student submissions that were stuck at "Your submission is being graded!". However, I am also getting stalled reruns when I test on known-good inputs.

**Comment by jbaileyhandle** [comment]
Note that I did not observe this issue on new submission of known-good inputs.

**Comment by james-perretta** [comment]
@jbaileyhandle The most likely scenarios here are either 1) another large rerun task is being processed (note that there are only 2 machines processing reruns compared to ~15 processing regular submissions), or 2) Some transient server issue is making things progress more slowly.

Looking at the logs for those machines, it looks like they've finished processing everything that was queued on them--has your rerun finished? I'm going to close this issue, send me an email if this hasn't resolved itself.

(P.S. Send me an email for things like this next time so that I can keep the issue tracker focused on feature requests and bugs and the like :) )
