### ISSUE TITLE
Feature Request: Add Student View

### ISSUE THREAD

**Issue by adviyer** [eecs-autograder/autograder.io#49]
A simple feature for instructors to switch to 'student view' to check which projects have been published would be great

Happy to work on it and put up a PR as well :)

**Comment by james-perretta** [comment]
To make sure I'm understanding correctly, this would be for instructors?

**Comment by adviyer** [comment]
Yes, I can see I wasn't very clear haha

**Comment by james-perretta** [comment]
Got it, thanks! If the scope of this is just seeing which projects have been published, then I would avoid calling it a "student view", since that seems to imply a more comprehensive feature where an instructor can fully interact as if they were a student. Would there maybe be some way to use icons in the list of projects to show which are published at a glance?

**Comment by adviyer** [comment]
You're right, calling it a student view might not be the best idea.
Having a check mark or similar icon which says 'published' when hovered should do the job I feel

**Comment by james-perretta** [comment]
Agreed, maybe an open/closed eye icon? You'd have to check what the version of fontawesome we use offers. Depending on how it looks, I might be fine with it even being always visible rather than having to hover. It should probably go with the name rather than with the other icons at the bottom of the panels?

**Comment by adviyer** [comment]
<img width="363" alt="image" src="https://github.com/eecs-autograder/autograder.io/assets/70266102/81090b36-88a5-4792-adf6-b774e1c0314d">
Yes, I think having the eye icons should help. Would above or to the left of the project settings icon be a good place?
Having it always visible would be more useful imo, we can have a toggle somewhere to disable it if users find it very annoying I guess.

**Comment by james-perretta** [comment]
Probably above the settings icon. I would put it on the same line as the project name, but justified all the way to the right.

**Comment by Normanwqn** [comment]
@adviyer, 

@broad-well, and I would like to work on this issue (and potentially more issues here) as part of our coursework for [EECS 481](https://eecs481.org/hw6.html), Software Engineering. Our work will be in [my fork](https://github.com/broad-well/ag-website-vue). Please feel free to message us if you would like to work with us on this feature as well.

**Comment by adviyer** [comment]
Sounds good, I might join later but feel free to take it on for now :)
